[package]
name = "ecstatic"
version = "0.0.1"
authors = ["Ian Gowen <ian@gowen.cc>"]
edition = "2018"
description = "Statically-typed ECS library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
